@startuml
skin rose

rectangle Planta
rectangle FaseCrecimiento
rectangle Jardín
rectangle Maceta
rectangle Tiempo
rectangle Ciclo
rectangle Semilla
rectangle Especie

Jardín *-- Maceta
Maceta *-- Planta
Semilla --> Maceta : se planta en
Planta - FaseCrecimiento : está en una 

Semilla --> Especie : pertenece a
Planta --> Especie : pertenece a 

FaseCrecimiento --> Tiempo : avanza con 
Planta --> Tiempo : crece con el


Tiempo --> Ciclo : avanza

@enduml