@startuml
skin rose
left to right direction 

actor Jugador
actor PasoDelTiempo

package Jardinería{
usecase Plantar
usecase Regar
usecase HacerCrecer
}
package Temporal{
usecase "Parar/Reanudar\nTiempo" as PararTiempo
usecase AvanzarCiclo
usecase SecarSuelo
usecase AvanzarTiempo
}

AvanzarCiclo .> SecarSuelo : includes
AvanzarTiempo .> AvanzarCiclo : includes

PasoDelTiempo -u- HacerCrecer
PasoDelTiempo -u- AvanzarTiempo

Jugador -- Plantar
Jugador -- Regar
Jugador -- PararTiempo
Jugador -- AvanzarCiclo

@enduml