@startuml
skin rose 

entity Maceta
entity Planta

control Regar

boundary Tierra
boundary Regadera

Regar -u-> Maceta : tienes planta?
Maceta -> Planta

Regar --> Tierra : mójate
Regar -l-> Regadera : dime qué maceta\nquieren regar

@enduml