@startuml
skin rose
left to right direction
skinparam actorstyle awesome

actor Jugador
actor PasoDelTiempo

usecase ReclamarPremio
usecase RecolectarHuevo
usecase FinalizarEvento

Jugador -- ReclamarPremio
Jugador -- RecolectarHuevo

PasoDelTiempo -u- FinalizarEvento
Jugador .. FinalizarEvento
@enduml