<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <RootNamespace>Plants</RootNamespace>
    <AssemblyName>Plants</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Charla DotNet\DotNet Ecosystem.puml" />
    <Content Include="Charla DotNet\UnityCtorDesignProblem.puml" />
    <Content Include="CursoRefactoring\1.puml" />
    <Content Include="CursoRefactoring\2.puml" />
    <Content Include="CursoRefactoring\3.puml" />
    <Content Include="CursoRefactoring\4.puml" />
    <Content Include="CursoRefactoring\5.puml" />
    <Content Include="Properties\Analysis.puml" />
    <Content Include="Properties\Contract" />
    <Content Include="Properties\DomainModel.puml" />
    <Content Include="Properties\Requirements.md" />
    <Content Include="Properties\RequirementsToDomain" />
    <Content Include="Properties\UseCases.puml" />
    <Content Include="Properties\UseCasesSpecification.md" />
  </ItemGroup>

</Project>