<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Plants</RootNamespace>
    <AssemblyName>Plants</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="CursoRefactoring\*.puml" />
    <Content Include="Properties\Analysis.puml" />
    <Content Include="Properties\Contract" />
    <Content Include="Properties\DomainModel.puml" />
    <Content Include="Properties\Requirements.md" />
    <Content Include="Properties\RequirementsToDomain" />
    <Content Include="Properties\UseCases.puml" />
    <Content Include="Properties\UseCasesSpecification.md" />
  </ItemGroup>

</Project>