@startuml
skin rose
skinparam actorstyle awesome
left to right direction

actor UsuarioNoLogueado <<NotLoggedUser>>
actor UsuarioDevice #technology
actor UsuarioProvider #application
actor Subscriptor
actor GooglePlay <<Not-Human>> #lightgray

package Network{
    usecase Subscribirse
}

usecase LoguearseAutomáticamente <<Autologin>>
usecase VincularseConGooglePlay

UsuarioDevice --> VincularseConGooglePlay
UsuarioProvider <-- VincularseConGooglePlay 

UsuarioNoLogueado --> LoguearseAutomáticamente
GooglePlay -u- LoguearseAutomáticamente
UsuarioDevice <-- LoguearseAutomáticamente #green : si va mal
UsuarioProvider <-- LoguearseAutomáticamente #blue 

UsuarioProvider --> Subscribirse
Subscriptor <-- Subscribirse 

@enduml