@startuml
skin rose
allow_mixing

actor "Cliente final" as Cliente

cloud "Nuestra organización" as NuestraOrganizacion{
node "Nuestro producto" as NuestroProducto
actor QA
}

Cliente - NuestroProducto : usa
QA -l- NuestroProducto : prueba

@enduml