@startuml
skin rose
allow_mixing
left to right direction

actor "Cliente final" as Cliente

cloud "Nuestra organización" as NuestraOrganizacion{
node "Nuestro producto" as NuestroProducto
actor QA
component "Nuestros sistemas" as NuestroSistema{
    component "Nuestro backend" as NuestroBackend{
        database "Nuestra\nbase de datos" as NuestraBaseDatos
        actor DBA
        DBA . NuestraBaseDatos : administra
        
        hexagon "Nuestro\ndominio" as NuestroDominio
        () Puertos
        NuestroDominio . Puertos : expone 

        component Adaptadores
        Adaptadores .l.|> Puertos : implementan
        Adaptadores --> NuestraBaseDatos
        
        actor "Analista\n(o lo que sea)" as Analista
        Analista -r-> NuestroDominio : trabaja en
        
        actor BackDev
        BackDev .. Adaptadores : desarrolla 
    }
   
    
    component "Nuestro frontend" as NuestroFrontend
    actor FrontDev
    FrontDev .. NuestroFrontend : desarrolla
   
    NuestroFrontend --> NuestroBackend : llama a
   
}
NuestroProducto <-- NuestroSistema : construyen
}

Cliente -- NuestroProducto : usa
QA -l- NuestroProducto : prueba

@enduml