@startuml
skin rose
skinparam cloudBorderColor Blue
skinparam cloudBackgroundColor #EEF
skinparam componentstyle uml1

cloud ".NET Core Ecosystem\n(.NET 6/7/8+...)" as NetCore <<evolving>> {
    [ASP.NET Core] #application
    [Blazor] #application 
    [Entity Framework Core] #application
    [MAUI] #application
    [Azure SDK] #application
    [Minimal APIs] #application
    [New C# Features] <<as of 8.0>> #application
    collections ManyOtherNewStuff #application
}

cloud ".NET Framework" as NetFramework <<legacy>> #lightgray {
    [Some New C# Features] <<up to 7.x>> #azure
}

node "Unity" #business {
    [UnityEditor]
    [UnityEngine]
    [Unity Test Framework]
    collections SomeOtherStuff
}

Unity -> NetFramework
Unity ...> NetCore : still waiting for years!\nofficial discussion fades out around 2022-2023...

@enduml
